github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false

vscode:
  extensions:
    - donjayamanne.githistory
    - EditorConfig.EditorConfig
